- hosts: all
  become: true
  tasks:
    - name: Update packages
      apt:
        name: "*"
        state: latest
    - name: Update snap packages
      shell: sudo snap refresh
    - name: Install DBeaver CE
      shell: sudo snap install dbeaver-ce
