- hosts: all
  become: true
  tasks:
    - name: Update packages
      apt:
        name: "*"
        state: latest
    - name: Add repository key
      shell: wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
    - name: Add repository to apt sources list
      shell: echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list
    - name: Install DBeaver CE
      shell: sudo apt install dbeaver-ce
